@@ -1,24 +1,30 @@
name: Build and Deploy
name: Test, Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
  test-build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build
      - name: Run tests
        run: npm run test

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          folder: dist
